stages:
  - build
  - test
  - deploy

default:
  image: alpine

build_genderize_microservice:
  stage: build
  script:
    - echo "This job builds something."

test_genderize_microservice:
  stage: test
  needs: [build_genderize_microservice]
  script:
    - echo "This job tests something."

deploy_genderize_microservice:
  stage: deploy
  needs: [test_genderize_microservice]
  script:
    - echo "This job deploys something."
  environment: production
