services:
  server:
    #build:
    #  context: ./
    #  dockerfile: server.Dockerfile
    image: "$CI_REGISTRY_IMAGE/$MICRO_PATH:$DEVELOP_BRANCH_NAME"
    container_name: genderize_server
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - "3000:3000"
    expose:
      - 3000
    healthcheck:
      #test: wget --no-verbose --tries=1 --spider http://localhost:3000/api || exit 1
      test: curl -f http://localhost:3000/api
      interval: 20s
      retries: 5
      start_period: 20s
      timeout: 15s
  testing:
    build:
      context: ./
      dockerfile: testing.Dockerfile
      args:
        - SERVER=http://genderize_server:3000 #Name of the above container, sevice "server".
    container_name: genderize_testing
    depends_on:
      #- server
      server:
        condition: service_healthy
