stages:
  - build
  - test

variables:
  MICRO_PATH: "micro_agify"

image: docker:cli
services:
  - docker:dind

build_feature:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd "$MICRO_PATH"
    - docker build --pull -t "$CI_REGISTRY_IMAGE/$MICRO_PATH:$CI_COMMIT_REF_SLUG" --file server.Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE/$MICRO_PATH:$CI_COMMIT_REF_SLUG"

test_feature:
  stage: test
  needs: [build_feature]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd "$MICRO_PATH"
    - docker compose -f feature-compose.yaml up --exit-code-from testing
    - docker compose -f feature-compose.yaml down --rmi all -v --remove-orphans
