stages:
  - build
  - test
  - post-build
  - deploy
  - delivery

variables:
  MICRO_PATH: "micro_agify"
  DOCKER_IMAGE_NAME: "f64franco/micro-agify"

image: docker:cli
services:
  - docker:dind

build_main_agify:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd "$MICRO_PATH"
    - docker build --pull -t "$CI_REGISTRY_IMAGE/$MICRO_PATH:$MAIN_BRANCH_NAME" --file server.Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE/$MICRO_PATH:$MAIN_BRANCH_NAME"

test_main_agify:
  stage: test
  needs: [build_main_agify]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd "$MICRO_PATH"
    #- docker compose up --abort-on-container-exit
    - docker compose -f main-compose.yaml up --exit-code-from testing
    - docker compose -f main-compose.yaml down --rmi all -v --remove-orphans

deploy_main_agify:
  stage: deploy
  needs: [test_main_agify]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull "$CI_REGISTRY_IMAGE/$MICRO_PATH:$MAIN_BRANCH_NAME"
    - docker tag "$CI_REGISTRY_IMAGE/$MICRO_PATH:$MAIN_BRANCH_NAME" "$DOCKER_IMAGE_NAME:$MAIN_BRANCH_NAME"
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    - docker push "$DOCKER_IMAGE_NAME:$MAIN_BRANCH_NAME"
    - docker rmi "$CI_REGISTRY_IMAGE/$MICRO_PATH:$MAIN_BRANCH_NAME" "$DOCKER_IMAGE_NAME:$MAIN_BRANCH_NAME"
  environment: production
