stages:
  - test

test_request:
  stage: test
  script:
    - echo "TEST MR"
    - echo "This job runs in merge request pipelines"
    - echo "$CI_COMMIT_BRANCH"
    - echo "$CI_COMMIT_REF_NAME"
    - echo "$CI_DEFAULT_BRANCH"
    - echo "$CI_OPEN_MERGE_REQUESTS"
    - echo "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
    - echo "$CI_MERGE_REQUEST_SOURCE_BRANCH_PROTECTED"
    - echo "$CI_MERGE_REQUEST_SOURCE_BRANCH_SHA"
    - echo "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    - echo "$CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED"
    - echo "$CI_MERGE_REQUEST_TARGET_BRANCH_SHA"
    - echo "$CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME"
    - echo "$CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_SHA"
    - echo "$CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME"
    - echo "$CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_SHA"
    - echo "GitLab CI/CD | Print all environment variables"
    - env
  rules:
    - if: $CI_MERGE_REQUEST_ID
  # Otra forma de ejecutar cuando éste pipeline se ejecuta a través de "trigger:include"
  #rules:
  #  - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
