stages:
  - build
  - test

build_mr:
  stage: build
  script:
    - echo "BUILD MR"
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

test_mr:
  stage: test
  needs: [build_mr]
  script:
    - echo "TEST MR"
