stages:
  - build
  - test
  - post-build

image: docker:cli
services:
  - docker:dind

build_request:
  stage: build
  script:
    - echo "BUILD MR"
    - echo "$CI_COMMIT_BRANCH"
    - echo "$CI_COMMIT_REF_NAME"
    - echo "$CI_OPEN_MERGE_REQUESTS"
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

test_request:
  stage: test
  needs: [build_request]
  script:
    - echo "TEST MR"
    - echo "This job runs in merge request pipelines"
    - echo "$CI_COMMIT_BRANCH"
    - echo "$CI_COMMIT_REF_NAME"
    - echo "$CI_DEFAULT_BRANCH"
    - echo "$CI_OPEN_MERGE_REQUESTS"
    - echo "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
    - echo "$CI_MERGE_REQUEST_SOURCE_BRANCH_PROTECTED"
    - echo "$CI_MERGE_REQUEST_SOURCE_BRANCH_SHA"
    - echo "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    - echo "$CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED"
    - echo "$CI_MERGE_REQUEST_TARGET_BRANCH_SHA"
    - echo "$CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME"
    - echo "$CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_SHA"
    - echo "$CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME"
    - echo "$CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_SHA"
    - echo "GitLab CI/CD | Print all environment variables"
    - env
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
  # Otra forma de ejecutar éste pipeline que fue llamado desde un padre, es decir un "trigger:include:"
  #rules:
  #  - if: $CI_MERGE_REQUEST_ID

post:
  stage: post-build
  needs: [test_request]
  script:
    - echo "POST-BUILD -> Despliegue a kubernetes"
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
