stages:
  - microservices

micro_agify:
  stage: microservices
  trigger:
    include: micro_agify/.agify-pipeline.yml
  rules:
    - changes:
        - micro_agify/*

micro_genderize:
  stage: microservices
  trigger:
    include: micro_genderize/.genderize-pipeline.yml
  rules:
    - changes:
        - micro_genderize/*

micro_middleware:
  stage: microservices
  trigger:
    include: middleware/.middleware-pipeline.yml
  rules:
    - changes:
        - middleware/*
