apiVersion: v1
kind: Service
metadata:
  name: micro3-service
spec:
  selector:
    app: micro3
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30003
