stages:
  - build
  - test
  - deploy

default:
  image: alpine

variables:
  GLOBAL_VAR: "A global variable"

build_agify:
  stage: build
  variables:
    JOB_VAR: "A job variable"
  script:
    - echo "Variables are '$CI_REGISTRY_IMAGE' and '$CI_COMMIT_REF_SLUG'"
    - echo "Variables2 are '$CI_REGISTRY_USER' , '$CI_REGISTRY_PASSWORD' and '$CI_REGISTRY'"
    - echo "Variables3 are '$DOCKER_IMAGE_NAME' , '$CI_COMMIT_BRANCH' and '$CI_DEFAULT_BRANCH'"
    - echo "changed 5"
    - echo "Variables6 are '$GLOBAL_VAR' and '$JOB_VAR'"
    - echo "Variables7 are '$CI_JOB_TOKEN' and ''"

test_agify:
  stage: test
  needs: [build_agify]
  script:
    - echo "This job tests something."

deploy_agify:
  stage: deploy
  needs: [test_agify]
  script:
    - echo "This job deploys something."
  environment: production
