stages:
  - build
  - test
  - post-build
  - deploy
  - delivery

variables:
  MICRO_PATH: "micro_agify"
  DOCKER_IMAGE_NAME: "f64franco/micro-agify"

build_agify:
  image: docker:cli
  stage: build
  services:
    - docker:dind
  before_script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
  script:
    - cd "$MICRO_PATH"
    - docker build --pull -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"

test_agify:
  stage: test
  needs: [build_agify]
  script:
    - echo "This job tests something."

deploy_agify:
  stage: deploy
  needs: [test_agify]
  script:
    - echo "This job deploys something."
  environment: production
