stages:
  - build
  - test
  - post-build
  - deploy
  - delivery

build_agify:
  stage: build
  script:
    - echo "EMPTY"

test_agify:
  stage: test
  needs: [build_agify]
  script:
    - echo "This job tests something."

deploy_agify:
  stage: deploy
  needs: [test_agify]
  script:
    - echo "This job deploys something."
  environment: production
