stages:
  - build
  - test
  - post-build
  - deploy
  - delivery

variables:
  MICRO_PATH: "micro_agify"
  DOCKER_IMAGE_NAME: "f64franco/micro-agify"

build_develop_agify:
  image: docker:cli
  stage: build
  services:
    - docker:dind
  before_script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$DEVELOP_BRANCH_NAME"]]; then
        cd "$MICRO_PATH"
        docker build --pull -t "$DOCKER_IMAGE_NAME:$DEVELOP_BRANCH_NAME" .
        docker push "$DOCKER_IMAGE_NAME:$DEVELOP_BRANCH_NAME"
      fi

test_agify:
  stage: test
  needs: [build_develop_agify]
  script:
    - echo "This job tests something."

deploy_agify:
  stage: deploy
  needs: [test_agify]
  script:
    - echo "This job deploys something."
  environment: production
