stages:
  - build
  - test
  - post-build
  - deploy
  - delivery

variables:
  MICRO_PATH: "micro_agify"
  DOCKER_IMAGE_NAME: "f64franco/micro-agify"
  LOCAL_DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE

image: docker:cli
services:
  - docker:dind

build_develop_agify:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd "$MICRO_PATH"
    - docker build --pull -t "$LOCAL_DOCKER_IMAGE_NAME:$DEVELOP_BRANCH_NAME" .
    - docker push "$LOCAL_DOCKER_IMAGE_NAME:$DEVELOP_BRANCH_NAME"
  rules:
    - if: $CI_COMMIT_BRANCH == $DEVELOP_BRANCH_NAME

test_develop_agify:
  stage: test
  needs: [build_develop_agify]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull "$LOCAL_DOCKER_IMAGE_NAME:$DEVELOP_BRANCH_NAME"
    - echo "This job tests something. PULLED"
  rules:
    - if: $CI_COMMIT_BRANCH == $DEVELOP_BRANCH_NAME

deploy_develop_agify:
  stage: deploy
  needs: [test_develop_agify]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    #- echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
  script:
    - docker pull "$LOCAL_DOCKER_IMAGE_NAME:$DEVELOP_BRANCH_NAME"
    - docker tag "$LOCAL_DOCKER_IMAGE_NAME:$DEVELOP_BRANCH_NAME" "$DOCKER_IMAGE_NAME:$DEVELOP_BRANCH_NAME"
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    - docker push "$DOCKER_IMAGE_NAME:$DEVELOP_BRANCH_NAME"
  rules:
    - if: $CI_COMMIT_BRANCH == $DEVELOP_BRANCH_NAME
  environment: production
