stages:
  - build
  - test
  - deploy

default:
  image: alpine

build_agify_microservice:
  stage: build
  script:
    - echo "This job builds something."

test_agify_microservice:
  stage: test
  needs: [build_agify_microservice]
  script:
    - echo "This job tests something."

deploy_agify_microservice:
  stage: deploy
  needs: [test_agify_microservice]
  script:
    - echo "This job deploys something."
  environment: production
