apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: $NAMESPACE
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
  type: NodePort
