kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: gitlab-runners-namespace
  name: deployer
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["services", "deployments", "replicasets", "pods", "configmap"]
    verbs: ["*"]
