stages:
  - build
  - test
  - deploy

default:
  image: alpine

build_middleware:
  stage: build
  script:
    - echo "This job builds something."

test_middleware:
  stage: test
  needs: [build_middleware]
  script:
    - echo "This job tests something."

deploy_middleware:
  stage: deploy
  needs: [test_middleware]
  script:
    - echo "This job deploys something."
  environment: production
