stages:
  - build
  - test
  - post-build
  - deploy

image: docker:cli
services:
  - docker:dind

build_develop:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd "$MICRO_PATH"
    - docker build --pull -t "$CI_REGISTRY_IMAGE/$MICRO_PATH:$DEVELOP_BRANCH_NAME" --file server.Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE/$MICRO_PATH:$DEVELOP_BRANCH_NAME"

test_develop:
  stage: test
  needs: [build_develop]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd "$MICRO_PATH"
    #- docker compose up --abort-on-container-exit
    - docker compose up --exit-code-from testing
    - docker compose down --rmi all -v --remove-orphans

post_build:
  stage: post-build
  needs: [test_develop]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull "$CI_REGISTRY_IMAGE/$MICRO_PATH:$DEVELOP_BRANCH_NAME"
    - docker tag "$CI_REGISTRY_IMAGE/$MICRO_PATH:$DEVELOP_BRANCH_NAME" "$DOCKER_IMAGE_NAME:$DEVELOP_BRANCH_NAME"
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    - docker push "$DOCKER_IMAGE_NAME:$DEVELOP_BRANCH_NAME"
    - docker rmi "$CI_REGISTRY_IMAGE/$MICRO_PATH:$DEVELOP_BRANCH_NAME" "$DOCKER_IMAGE_NAME:$DEVELOP_BRANCH_NAME"

deploy_develop:
  stage: deploy
  image: bitnami/kubectl
  needs: [post_build]
  script:
    - cd "$KUBERNETES_FILES"
    - export IMAGE_TO_DEPLOY=$DOCKER_IMAGE_NAME:$DEVELOP_BRANCH_NAME
    - envsubst < deployment.yaml | kubectl apply --namespace $NAMESPACE -f -
    - kubectl apply --namespace $NAMESPACE -f service.yaml
    - echo "Deploy to Kubernetes =)"
