stages:
  - build
  - test
  - delivery
  - deploy

image: docker:cli
services:
  - docker:dind

build_main:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd "$MICRO_PATH"
    - docker build --pull -t "$CI_REGISTRY_IMAGE/$MICRO_PATH:$MAIN_BRANCH_NAME" --file server.Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE/$MICRO_PATH:$MAIN_BRANCH_NAME"

test_main:
  stage: test
  needs: [build_main]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd "$MICRO_PATH"
    #- docker compose up --abort-on-container-exit
    - docker compose up --exit-code-from testing
    - docker compose down --rmi all -v --remove-orphans

delivery_main:
  stage: delivery
  needs: [test_main]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull "$CI_REGISTRY_IMAGE/$MICRO_PATH:$MAIN_BRANCH_NAME"
    - docker tag "$CI_REGISTRY_IMAGE/$MICRO_PATH:$MAIN_BRANCH_NAME" "$DOCKER_IMAGE_NAME:$MAIN_BRANCH_NAME"
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    - docker push "$DOCKER_IMAGE_NAME:$MAIN_BRANCH_NAME"
    - docker rmi "$CI_REGISTRY_IMAGE/$MICRO_PATH:$MAIN_BRANCH_NAME" "$DOCKER_IMAGE_NAME:$MAIN_BRANCH_NAME"
  environment: production

deploy_main:
  stage: deploy
  image: bitnami/kubectl
  needs: [delivery_main]
  script:
    - cd "$KUBERNETES_FILES"
    - kubectl apply --namespace $NAMESPACE -f main-deployment.yaml
    - kubectl apply --namespace $NAMESPACE -f service.yaml
    - echo "Deployed to namespace $NAMESPACE =)"
